<?php
// This file generated by Propel 1.6.9 convert-conf target
return array (
  'PropelORM\\Model\\Album' => 'Album.php',
  'PropelORM\\Model\\AlbumPeer' => 'AlbumPeer.php',
  'PropelORM\\Model\\AlbumQuery' => 'AlbumQuery.php',
  'PropelORM\\Model\\Songs' => 'Songs.php',
  'PropelORM\\Model\\SongsPeer' => 'SongsPeer.php',
  'PropelORM\\Model\\SongsQuery' => 'SongsQuery.php',
  'PropelORM\\Model\\map\\AlbumTableMap' => 'map/AlbumTableMap.php',
  'PropelORM\\Model\\map\\SongsTableMap' => 'map/SongsTableMap.php',
  'PropelORM\\Model\\om\\BaseAlbum' => 'om/BaseAlbum.php',
  'PropelORM\\Model\\om\\BaseAlbumPeer' => 'om/BaseAlbumPeer.php',
  'PropelORM\\Model\\om\\BaseAlbumQuery' => 'om/BaseAlbumQuery.php',
  'PropelORM\\Model\\om\\BaseSongs' => 'om/BaseSongs.php',
  'PropelORM\\Model\\om\\BaseSongsPeer' => 'om/BaseSongsPeer.php',
  'PropelORM\\Model\\om\\BaseSongsQuery' => 'om/BaseSongsQuery.php',
);