<select id="select01" style="margin-top:5px; width: 100px"
        OnChange="javascript:window.location.replace(changeLang(this.value));">
    <?php
    foreach ($this->lang as $key => $value) { 
        $selected = ($value === $this->selected) ? 'selected' : '';
        echo "<option value=\"$value\" $selected>$key</option>";
    }?>
</select>
<script>
    function changeLang(lang) {
        var newUrl = location.href.replace(/[a-z]{2}-[A-Z]{2}/,lang);
        if (newUrl != location.href) {
            return newUrl;
        }
        var n = location.href.indexOf('/',7);
        if (location.href.substr(n) == '/') {
            return location.href.substr(0,n) + '/' + lang;
        }
        return location.href.substr(0,n) + '/' + lang + location.href.substr(n);
    }
</script>